name: Django unit tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the test
      run: make build

    - name: Start the database
      run: make up

    - name: Wait for the database
      run: sleep 10

    - name: Set up the database
      run: make migrations

    - name: Run migrations
      run: make migrate

    - name: Run the test
      run: make test

    - name: Clean up
      run: make down